### ISSUE TITLE
SDK APIs does not work in release mode

### ISSUE THREAD

**Issue by ParitoshVaidya** [ttlock/ttlock_flutter#3]
App only works in debug mode. Once release apk is created, lock features stop working.

**Comment by ttlock** [comment]
5. you need config buildTypes in build.gradle file.like this:

    buildTypes {
        release {
            shrinkResources false
        }
    }

**Comment by ttlock** [comment]
Please config buildTypes in build.gradle file.like this:

```
buildTypes {
release {
shrinkResources false
}
}
```

**Comment by SDS712** [comment]
Yes, thank You.
Though in our case it worked after adding `minifyEnabled false` flag along with `shrinkResources false` in the release block.

So it worked with following config
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            shrinkResources false
            minifyEnabled false
        }
    }
```
